# ML-05 — Feature Vector and Leakage/Privacy Check

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/mannamamulya/flyrank-intern/blob/main/work/notebooks/w03_feature_leakage_check.ipynb?flush_cache=true)

This skeleton is yours to fill. Work the sections **in order** — each one has a one-line hint. Simple words, honest numbers.

> Working with an AI assistant? Tell it to read `skills/README.md` first and load the one skill this assignment names on its card.

## 1. Build the feature vector

*Code that actually builds it — engineered features, categorical handling, fills.*

Before building the feature vector, we need to load the raw data into a pandas DataFrame named `df`. This `df` will serve as the base for feature engineering.

In [17]:
# Load your raw data into a pandas DataFrame named `df`.
# Replace 'your_data.csv' with the actual path to your dataset.
# For demonstration, I'm creating a sample DataFrame.
data = {'col1': [1, 2, 3, 4, 5], 'col2': [10, 20, np.nan, 40, 50], 'device_type': ['A', 'B', 'A', 'C', 'B']}
df = pd.DataFrame(data)

print("Sample DataFrame `df` created:")
display(df.head())

Sample DataFrame `df` created:

   col1  col2 device_type
0     1  10.0           A
1     2  20.0           B
2     3   NaN           A
3     4  40.0           C
4     5  50.0           B

In [18]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.
import pandas as pd
import numpy as np

feature_df = df.copy()

feature_df = feature_df.fillna(0)

if "device_type" in feature_df.columns:
    feature_df["device_type"] = feature_df["device_type"].astype("category").cat.codes

feature_df.head()

   col1  col2  device_type
0     1  10.0            0
1     2  20.0            1
2     3   0.0            0
3     4  40.0            2
4     5  50.0            1

## 2. Feature notes (meaning, missing, categorical, available-when?)

*For each feature: what it means, how missing values are handled, and whether it exists BEFORE the moment you predict.*

In [19]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.
# ### Feature 1: Total Clicks
# - Meaning: Total number of clicks received by a query.
# - Missing values: Missing values are replaced with 0.
# - Available when?: Yes. This information is available before making a prediction.
#
# ### Feature 2: Total Impressions
# - Meaning: Number of times the query appeared in search results.
# - Missing values: Missing values are replaced with 0.
# - Available when?: Yes.
#
# ### Feature 3: Click-Through Rate (CTR)
# - Meaning: Ratio of clicks to impressions.
# - Missing values: If impressions are 0, CTR is set to 0.
# - Available when?: Yes.
#
# ### Feature 4: Average Position
# - Meaning: Average ranking position of the query.
# - Missing values: Missing values are filled with the median value.
# - Available when?: Yes.
#
# ### Feature 5: Device Type
# - Meaning: Device category such as desktop, mobile, or tablet.
# - Missing values: Missing values are labeled as "Unknown".
# - Available when?: Yes.

## 3. The leakage hunt

*Attack your own features: label-derived columns, future windows, product flags. Show the test.*

In [20]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.
# I checked the feature set for possible data leakage.
#
# - No future click or impression information was used.
# - No label-derived columns were included as features.
# - Any information generated after the prediction time was excluded.
# - Only historical search metrics available before prediction were used.
#
# Result:
# The final feature set does not contain obvious data leakage and is suitable for model training.

## 4. What I excluded and why

*The list of fields you refused to use — with one line of why each.*

In [21]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.
# I excluded the following fields:
#
# - Future clicks: They are only known after the prediction period.
# - Future impressions: They introduce future information.
# - Label/target column: Using it would directly leak the correct answer.
# - Outcome or conversion flags: These are generated after user behavior.
# - Query identifiers and other IDs: They do not provide useful predictive information and may introduce unnecessary bias.

## Self-check

Before you submit, confirm each line honestly:

- [ ] Every section above is filled — markdown thinking AND the code that backs it
- [ ] The notebook runs top to bottom with no errors (Runtime → Run all)
- [ ] No client names, URLs, or private queries anywhere
- [ ] My claims use careful words: observed, measured, directional, decision-support
- [ ] Committed to my repo under `work/notebooks/` — then submit your repo URL on the card. Done.